/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import calculator.Calculator;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        Calculator calculator = new Calculator();
        calculator.run();
    }
}
