/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.java.calculator;

import com.programmers.java.calculator.engine.Calculation;
import com.programmers.java.calculator.engine.model.Arithmetic;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class CalculatorTest {
    private Calculation calculation;

    @BeforeEach
    public void setup() {
        calculation = new Calculation();
    }

    @Test
    public void checkToPostfix() {
        Assertions.assertEquals(
                calculation.toPostfix(new Arithmetic(new String[]{"1", "+", "2", "*", "3", "-", "4"})).toString(),
                new Arithmetic(new String[]{"1", "2", "3", "*", "+", "4", "-"}).toString());
    }

    @Test
    public void checkCalculation() {
        Assertions.assertEquals(
                calculation.doCalculation(new Arithmetic(new String[]{"1", "2", "3", "*", "+", "4", "-"}))
                        .orElseThrow(), 3.0);
    }

    @Test
    public void checkDivisionByZero() {
        Assertions.assertEquals(
                calculation.doCalculation(new Arithmetic(new String[]{"1", "0", "/"}))
                        .orElseThrow(), Double.POSITIVE_INFINITY);

        Assertions.assertEquals(
                calculation.doCalculation(new Arithmetic(new String[]{"-1", "0", "/"}))
                        .orElseThrow(), Double.NEGATIVE_INFINITY);

        Assertions.assertEquals(
                calculation.doCalculation(new Arithmetic(new String[]{"0", "0", "/"}))
                        .orElseThrow(), Double.NaN);
    }
}
