/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caculator;

import lombok.NoArgsConstructor;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Optional;
import java.util.Scanner;

@NoArgsConstructor
public class App {
    private static final int HISTORY = 1;
    private static final int CALCULATOR = 2;
    private static ArrayList<StringBuilder> history = new ArrayList<>();
    private static Calculator cal;
    private static Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        while(true) {
            print("1.조회\n2.계산");
            try {
                int menu = getMenuNum();
                switch(menu) {
                    case HISTORY:
                        print(history);
                        break;
                    case CALCULATOR:
                        StringBuilder formula = getFormula();
                        if(cal.isFormula(formula)) {
                            Float result = cal.calculate(formula);
                            saveFormula(formula, result);
                            print(result);
                        }
                        else {
                            print("올바른 계산식을 입력하세요.");
                        }
                        break;
                    default:
                        print("1과 2 중 입력하세요.");
                }
            } catch (Exception e) {
                print("1과 2 중 입력하세요.");
                e.printStackTrace();
            }
        }
    }

    public static int getMenuNum() {
        int data = sc.nextInt();
        sc.nextLine();
        return data;
    }

    public static StringBuilder getFormula() {
        String data = sc.nextLine();
        return new StringBuilder(data.replaceAll(" ",""));
    }

    public static void saveFormula(StringBuilder formula, Float result) {
        formula.append(" = ");
        formula.append(new DecimalFormat("#.##").format(result));
        history.add(formula);
    }

    public static void print(ArrayList<StringBuilder> list) {
        Optional<ArrayList<StringBuilder>> tmp = Optional.ofNullable(list);
        tmp.ifPresent((value)->{value.forEach(System.out::println);});
    }

    public static void print(String msg) {
        System.out.println(msg);
    }

    public static void print(float msg) {
        System.out.println(new DecimalFormat("#.##").format(msg));
    }
}
