/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.mission;

import com.programmers.mission.controller.CalculationController;
import com.programmers.mission.view.ConsoleView;

public class App {
	public static void main(String[] args) {
		ConsoleView consoleView = new ConsoleView();
		CalculationController calculationController = new CalculationController(consoleView, consoleView);
		calculationController.runCalculationProgram();
	}
}
