/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.mission;

import com.programmers.mission.controller.CalculationController;
import com.programmers.mission.model.CalculationHistoryManager;
import com.programmers.mission.model.CalculationResult;
import com.programmers.mission.model.HistoryManager;
import com.programmers.mission.validation.CalculatorValidation;
import com.programmers.mission.view.ConsoleView;

public class App {
	public static void main(String[] args) {
		ConsoleView consoleView = new ConsoleView();
		CalculatorValidation calculatorValidation = new CalculatorValidation();
		HistoryManager<CalculationResult> calculationHistoryManager = new CalculationHistoryManager();
		CalculationController calculationController = new CalculationController.CalculationControllerBuilder()
				.Input(consoleView)
				.Output(consoleView)
				.Validation(calculatorValidation)
				.HistoryManager(calculationHistoryManager)
				.build();

		calculationController.runCalculationProgram();
	}
}

