/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.oop;

import java.io.IOException;

import com.programmers.oop.view.Console;

public class Main {

    public static void main(String[] args) throws IOException {
        CalculatorMachine calculatorMachine = new CalculatorMachine(new Console());
        calculatorMachine.start();
    }
}
