/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programmers.java.calulator;

import programmers.java.calulator.common.calculator.StackCalculator;
import programmers.java.calulator.console.menu.MenuHandler;
import programmers.java.calulator.console.reader.ConsoleReader;
import programmers.java.calulator.console.repository.MapRepository;
import programmers.java.calulator.console.runner.ConsoleRunner;
import programmers.java.calulator.console.writer.ConsoleWriter;

public class App {

    public static void main(String[] args) {
        new ConsoleRunner(new MenuHandler(new ConsoleWriter(), new StackCalculator(), new ConsoleReader(), MapRepository.getInstance())).run();
    }
}
