/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers;

import com.programmers.calculator.Calculator;
import com.programmers.calculator.Console;
import com.programmers.calculator.repository.HistoryRepository;

public class App {

    public static void main(String[] args) {
        Console console = new Console();
        HistoryRepository historyRepository = new HistoryRepository();
        new Calculator(console, console, historyRepository).run();
    }
}
