/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers;

import com.programmers.controller.CalculatorController;

public class CalculatorApplication {
	
    public static void main(String[] args) {
	    CalculatorController calculatorController = new CalculatorController();
		calculatorController.run();
    }
	
}
