/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.devcourse;

import com.programmers.devcourse.calculator.IntegerCalculator;

public class CalculationRunner {
    public static void main(String[] args) {
        new IntegerCalculator().run();
    }
}
