/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class Main {

    public static void main(String[] args) {
        System.out.println("aa");
    }
}
