/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers;

import static org.assertj.core.api.Assertions.*; // assertThat

import com.programmers.calculator.Console;
import com.programmers.calculator.model.Expression;
import com.programmers.calculator.repository.HistoryRepository;
import org.junit.jupiter.api.Test;

class AppTest {
    Console console = new Console();
    HistoryRepository historyRepository = new HistoryRepository();

    @Test
    void 간단한_계산_테스트() {
        // given
        Expression plus = new Expression("1 + 3");
        Expression minus = new Expression("5 - 3");
        Expression multiply = new Expression("4 * 3");
        Expression divide = new Expression("6 / 3");

        // when
        int plusResult = plus.getResult();
        int minusResult = minus.getResult();
        int multiplyResult = multiply.getResult();
        int divideResult = divide.getResult();

        // then
        assertThat(plusResult).isEqualTo(4);
        assertThat(minusResult).isEqualTo(2);
        assertThat(multiplyResult).isEqualTo(12);
        assertThat(divideResult).isEqualTo(2);
    }
}
